spring:
  application:
    name: rq_admin
  datasource:
    url: jdbc:mysql://localhost:3306/rq_admin
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
  # profiles:
  #   active: dev
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'

# 文件上传配置
file:
  upload:
    path: uploads
    max-size: 10485760  # 10MB
  jackson:
    #    date-format: yyyy-MM-dd HH:mm:ss
    #    time-zone: GMT+8
    serialization:
#      write-dates-as-timestamps: false
#    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: org.example.rq_admin

knife4j:
  enable: true
  setting:
    language: zh_cn
#  basic:
#    username: user
#    password: 123456
#    enable: true

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler


application:
  security:
    jwt:
      secret-key: fq/iucJz9h4QkRTm+jqNy9/u9hjiumy40hjF91lCouqgtja8KjcEFv4I8aNIi6pB/dRCQFGJSvn6Js3L4gPOlg==
      expiration: 43200000